name       : totem-pl-parser
version    : 3.26.3
release    : 11
source     :
    - https://download.gnome.org/sources/totem-pl-parser/3.26/totem-pl-parser-3.26.3.tar.xz : 0efd01b8a0a9770d52fe7354d298874ed845449b88f3f78f49290729fc2d448d
homepage   : https://developer.gnome.org/totem-pl-parser/stable/
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : Totem playlist parser
description: |
    Totem playlist parser is a simple GObject-based library to parse a host of playlist formats.
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libquvi-0.9)
    - pkgconfig(libsoup-2.4)
    - libgcrypt-devel
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
