name       : totem-pl-parser
version    : 3.10.7
release    : 4
source     :
    - http://ftp.gnome.org/pub/gnome/sources/totem-pl-parser/3.10/totem-pl-parser-3.10.7.tar.xz : 9c8285bc3131faa309d5cba5a919d5166abc2b8cc5a0c850fe861be8b14e089c
homepage   : https://developer.gnome.org/totem-pl-parser/stable/
license    : LGPL-2.0
component  : desktop.gnome.core
summary    : Totem playlist parser
builddeps  :
    - pkgconfig(gmime-2.6)
    - pkgconfig(libarchive)
    - pkgconfig(libsoup-2.4)
    - libgcrypt-devel
description: |
    Totem playlist parser is a simple GObject-based library to parse a host of playlist formats.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
