name       : totem-pl-parser
version    : 3.26.0
release    : 8
source     :
    - https://download.gnome.org/sources/totem-pl-parser/3.26/totem-pl-parser-3.26.0.tar.xz : f153a53391e9b42fed5cb6ce62322a58e323fde6ec4a54d8ba4d376cf4c1fbcb
homepage   : https://developer.gnome.org/totem-pl-parser/stable/
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : Totem playlist parser
builddeps  :
    - pkgconfig(gmime-3.0)
    - pkgconfig(libarchive)
    - pkgconfig(libquvi-0.9)
    - pkgconfig(libsoup-2.4)
description: |
    Totem playlist parser is a simple GObject-based library to parse a host of playlist formats.
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
